# To limit exposure to denial of service attacks, change the host in endpoints below from 0.0.0.0 to a specific network interface.
# See https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/security-best-practices.md#safeguards-against-denial-of-service-attacks
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  httpcheck:
    targets:
      - endpoint: https://idir.uta.edu/bipartiteGraphUi/
        method: GET
      - endpoint: https://idir.uta.edu/bipartiteGraphApi/environ
        method: GET

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "localhost:1234"
    const_labels:
      server: idirserver12
    send_timestamps: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,prometheus]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug,prometheus]
